// ─── DADOS DOS JOGOS ──────────────────────────────────────────
const BASE_URL = 'https://f9-andrade.github.io/PedroRyangames2.0/games';

const GAMES_DATA = [
  { id:'1v1lol',                   name:'1v1.LOL',                    cat:'Ação',       tags:['multiplayer','tiro'],      featured:true  },
  { id:'2048',                     name:'2048',                       cat:'Puzzle',     tags:['números','clássico'],      featured:false },
  { id:'adarkroom',                name:'A Dark Room',                cat:'RPG',        tags:['texto','idle'],            featured:false },
  { id:'asciispace',               name:'ASCII Space',                cat:'Ação',       tags:['espaço','retrô'],          featured:false },
  { id:'assessmentexamination',    name:'Assessment Exam',            cat:'Puzzle',     tags:['quiz'],                    featured:false },
  { id:'asteroids',                name:'Asteroids',                  cat:'Clássico',   tags:['espaço','nave'],           featured:false },
  { id:'astray',                   name:'Astray',                     cat:'Puzzle',     tags:['labirinto','3D'],          featured:false },
  { id:'backcountry',              name:'Backcountry',                cat:'Corrida',    tags:['esqui'],                   featured:false },
  { id:'baldisbasics',             name:"Baldi's Basics",             cat:'Terror',     tags:['horror','escola'],         featured:false },
  { id:'basketballlegends',        name:'Basketball Legends',         cat:'Esporte',    tags:['basquete','multiplayer'],  featured:false },
  { id:'basketballstars',          name:'Basketball Stars',           cat:'Esporte',    tags:['basquete','multiplayer'],  featured:false },
  { id:'basketbrosio',             name:'BasketBros.io',              cat:'Esporte',    tags:['basquete','io'],           featured:false },
  { id:'basketrandom',             name:'Basketball Random',          cat:'Esporte',    tags:['basquete','casual'],       featured:false },
  { id:'bitlife',                  name:'BitLife',                    cat:'Simulação',  tags:['vida','escolhas'],         featured:true  },
  { id:'blackholesquare',          name:'Black Hole Square',          cat:'Puzzle',     tags:['física'],                  featured:false },
  { id:'bounceback',               name:'Bounce Back',                cat:'Casual',     tags:['reflexo'],                 featured:false },
  { id:'boxingrandom',             name:'Boxing Random',              cat:'Esporte',    tags:['boxe','multiplayer'],      featured:false },
  { id:'breaklock',                name:'Breaklock',                  cat:'Puzzle',     tags:['padrão'],                  featured:false },
  { id:'breakout',                 name:'Breakout',                   cat:'Clássico',   tags:['bola','blocos'],           featured:false },
  { id:'btd4',                     name:'Bloons TD 4',                cat:'Estratégia', tags:['tower defense'],           featured:true  },
  { id:'captaincallisto',          name:'Captain Callisto',           cat:'Aventura',   tags:['espaço','plataforma'],     featured:false },
  { id:'chess',                    name:'Chess',                      cat:'Estratégia', tags:['xadrez','clássico'],       featured:false },
  { id:'chromaincident',           name:'Chroma Incident',            cat:'Puzzle',     tags:['cores','lógica'],          featured:false },
  { id:'chromedino',               name:'Chrome Dino',                cat:'Clássico',   tags:['dinossauro','runner'],     featured:false },
  { id:'clickerheroes',            name:'Clicker Heroes',             cat:'Idle',       tags:['clicker','rpg'],           featured:false },
  { id:'clusterrush',              name:'Cluster Rush',               cat:'Ação',       tags:['plataforma'],              featured:true  },
  { id:'connect3',                 name:'Connect 3',                  cat:'Puzzle',     tags:['casual'],                  featured:false },
  { id:'cookieclicker',            name:'Cookie Clicker',             cat:'Idle',       tags:['clicker'],                 featured:true  },
  { id:'crossyroad',               name:'Crossy Road',                cat:'Casual',     tags:['pular'],                   featured:false },
  { id:'csgoclicker',              name:'CS:GO Clicker',              cat:'Idle',       tags:['clicker'],                 featured:false },
  { id:'cubefield',                name:'Cubefield',                  cat:'Ação',       tags:['esquivar','velocidade'],   featured:false },
  { id:'cubitomayhem',             name:'Cubito Mayhem',              cat:'Ação',       tags:['batalha'],                 featured:false },
  { id:'cuttherope',               name:'Cut the Rope',               cat:'Puzzle',     tags:['física','corda'],          featured:false },
  { id:'cuttheropeholiday',        name:'Cut the Rope Holiday',       cat:'Puzzle',     tags:['física'],                  featured:false },
  { id:'cuttheropetimetravel',     name:'Cut the Rope Time Travel',   cat:'Puzzle',     tags:['física'],                  featured:false },
  { id:'deathrun3d',               name:'Death Run 3D',               cat:'Ação',       tags:['corrida','obstáculos'],    featured:false },
  { id:'deepestsword',             name:'Deepest Sword',              cat:'Puzzle',     tags:['espada'],                  featured:false },
  { id:'doodlejump',               name:'Doodle Jump',                cat:'Casual',     tags:['pular'],                   featured:false },
  { id:'doom',                     name:'Doom',                       cat:'Ação',       tags:['fps','clássico'],          featured:true  },
  { id:'drawthehill',              name:'Draw the Hill',              cat:'Casual',     tags:['desenhar','física'],       featured:false },
  { id:'drift',                    name:'Drift',                      cat:'Corrida',    tags:['carro','drift'],           featured:false },
  { id:'drifthunters',             name:'Drift Hunters',              cat:'Corrida',    tags:['carro','drift'],           featured:true  },
  { id:'drivemad',                 name:'Drive Mad',                  cat:'Corrida',    tags:['carro','física'],          featured:false },
  { id:'ducklife',                 name:'Duck Life',                  cat:'Aventura',   tags:['pato'],                    featured:false },
  { id:'ducklife2',                name:'Duck Life 2',                cat:'Aventura',   tags:['pato'],                    featured:false },
  { id:'ducklife3',                name:'Duck Life 3',                cat:'Aventura',   tags:['pato'],                    featured:false },
  { id:'ducklife4',                name:'Duck Life 4',                cat:'Aventura',   tags:['pato'],                    featured:false },
  { id:'ducklife5',                name:'Duck Life 5',                cat:'Aventura',   tags:['pato'],                    featured:false },
  { id:'earntodie',                name:'Earn to Die',                cat:'Ação',       tags:['zumbi','carro'],           featured:false },
  { id:'edgenotfound',             name:'Edge Not Found',             cat:'Puzzle',     tags:['plataforma'],              featured:false },
  { id:'eggycar',                  name:'Eggy Car',                   cat:'Casual',     tags:['ovo','equilíbrio'],        featured:false },
  { id:'evilglitch',               name:'Evil Glitch',                cat:'Ação',       tags:['pixel','plataforma'],      featured:false },
  { id:'factoryballsforever',      name:'Factory Balls Forever',      cat:'Puzzle',     tags:['lógica'],                  featured:false },
  { id:'fireboyandwatergirlforesttemple', name:'Fireboy & Watergirl', cat:'Aventura',   tags:['cooperativo'],             featured:true  },
  { id:'flappy2048',               name:'Flappy 2048',                cat:'Casual',     tags:['flappy','números'],        featured:false },
  { id:'flappybird',               name:'Flappy Bird',                cat:'Clássico',   tags:['pássaro'],                 featured:false },
  { id:'flappyplane',              name:'Flappy Plane',               cat:'Casual',     tags:['avião'],                   featured:false },
  { id:'flightsimulator',          name:'Flight Simulator',           cat:'Simulação',  tags:['avião','3D'],              featured:false },
  { id:'fridaynightfunkin',        name:'Friday Night Funkin',        cat:'Ritmo',      tags:['música'],                  featured:true  },
  { id:'friendlyfire',             name:'Friendly Fire',              cat:'Ação',       tags:['tiro','multiplayer'],      featured:false },
  { id:'fruitninja',               name:'Fruit Ninja',                cat:'Casual',     tags:['fruta'],                   featured:false },
  { id:'geometrydash',             name:'Geometry Dash',              cat:'Ritmo',      tags:['música','plataforma'],     featured:true  },
  { id:'getawayshootoutnew',       name:'Getaway Shootout',           cat:'Ação',       tags:['multiplayer','tiro'],      featured:false },
  { id:'gladihoppers',             name:'Gladihoppers',               cat:'Esporte',    tags:['luta'],                    featured:false },
  { id:'googlesnake',              name:'Google Snake',               cat:'Clássico',   tags:['cobra'],                   featured:false },
  { id:'gopherkart',               name:'Gopher Kart',                cat:'Corrida',    tags:['kart'],                    featured:false },
  { id:'grindcraft',               name:'Grindcraft',                 cat:'Idle',       tags:['craft'],                   featured:false },
  { id:'hexgl',                    name:'HexGL',                      cat:'Corrida',    tags:['futurista','3D'],          featured:true  },
  { id:'hextris',                  name:'Hextris',                    cat:'Puzzle',     tags:['tetris'],                  featured:false },
  { id:'highwaytraffic',           name:'Highway Traffic',            cat:'Corrida',    tags:['esquivar'],                featured:false },
  { id:'konnekt',                  name:'Konnekt',                    cat:'Puzzle',     tags:['conectar'],                featured:false },
  { id:'learntofly',               name:'Learn to Fly',               cat:'Casual',     tags:['pinguim','voar'],          featured:false },
  { id:'letssurf',                 name:"Let's Surf",                 cat:'Casual',     tags:['surf'],                    featured:false },
  { id:'littlealchemy',            name:'Little Alchemy',             cat:'Puzzle',     tags:['elementos'],               featured:false },
  { id:'mergeroundracers',         name:'Merge Round Racers',         cat:'Idle',       tags:['merge'],                   featured:false },
  { id:'monkeymart',               name:'Monkey Mart',                cat:'Simulação',  tags:['mercado'],                 featured:true  },
  { id:'motoroadrash3d',           name:'Moto Road Rash 3D',          cat:'Corrida',    tags:['moto','3D'],               featured:false },
  { id:'motox3m',                  name:'Moto X3M',                   cat:'Corrida',    tags:['moto','obstáculos'],       featured:true  },
  { id:'ninjavsevilcorp',          name:'Ninja vs Evil Corp',         cat:'Ação',       tags:['ninja','plataforma'],      featured:false },
  { id:'omnombounce',              name:'Om Nom Bounce',              cat:'Casual',     tags:['bounce'],                  featured:false },
  { id:'ovo',                      name:'OvO',                        cat:'Plataforma', tags:['parkour','ágil'],          featured:true  },
  { id:'ovo2',                     name:'OvO 2',                      cat:'Plataforma', tags:['parkour','ágil'],          featured:false },
  { id:'packabunchas',             name:'Packabunchas',               cat:'Puzzle',     tags:['casual'],                  featured:false },
  { id:'pacman',                   name:'Pac-Man',                    cat:'Clássico',   tags:['fantasma','labirinto'],    featured:false },
  { id:'paperio',                  name:'Paper.io',                   cat:'Ação',       tags:['território','io'],         featured:false },
  { id:'particleclicker',          name:'Particle Clicker',           cat:'Idle',       tags:['física'],                  featured:false },
  { id:'pushback',                 name:'Push Back',                  cat:'Puzzle',     tags:['empurrar'],                featured:false },
  { id:'q1k3',                     name:'Q1K3',                       cat:'Ação',       tags:['fps','retrô'],             featured:false },
  { id:'r3',                       name:'R3',                         cat:'Ação',       tags:['espacial'],                featured:false },
  { id:'racer',                    name:'Racer',                      cat:'Corrida',    tags:['pixel'],                   featured:false },
  { id:'radiusraid',               name:'Radius Raid',                cat:'Ação',       tags:['nave','shooter'],          featured:false },
  { id:'redball4',                 name:'Red Ball 4',                 cat:'Plataforma', tags:['bola'],                    featured:false },
  { id:'retrobowl',                name:'Retro Bowl',                 cat:'Esporte',    tags:['futebol americano'],       featured:true  },
  { id:'retrohaunt',               name:'Retro Haunt',                cat:'Terror',     tags:['pixel','horror'],          featured:false },
  { id:'riddleschool2',            name:'Riddle School 2',            cat:'Aventura',   tags:['escola','puzzle'],         featured:false },
  { id:'ritz',                     name:'Ritz',                       cat:'Plataforma', tags:['rato'],                    featured:false },
  { id:'roadblocks',               name:'Road Blocks',                cat:'Puzzle',     tags:['trânsito'],                featured:false },
  { id:'rooftopsnipers',           name:'Rooftop Snipers',            cat:'Ação',       tags:['sniper','multiplayer'],    featured:false },
  { id:'run3',                     name:'Run 3',                      cat:'Corrida',    tags:['runner','espaço'],         featured:true  },
  { id:'scrapmetal3',              name:'Scrap Metal 3',              cat:'Corrida',    tags:['sucata'],                  featured:false },
  { id:'shuttledeck',              name:'Shuttle Deck',               cat:'Estratégia', tags:['cartas','espaço'],         featured:false },
  { id:'sketchbook04',             name:'Sketchbook',                 cat:'Casual',     tags:['desenho'],                 featured:false },
  { id:'sleepingbeauty',           name:'Sleeping Beauty',            cat:'Aventura',   tags:['conto'],                   featured:false },
  { id:'slitherio',                name:'Slither.io',                 cat:'Ação',       tags:['cobra','io','multiplayer'],featured:true  },
  { id:'slope',                    name:'Slope',                      cat:'Ação',       tags:['bola','3D','velocidade'],  featured:true  },
  { id:'slope2',                   name:'Slope 2',                    cat:'Ação',       tags:['bola','3D'],               featured:false },
  { id:'snake',                    name:'Snake',                      cat:'Clássico',   tags:['cobra'],                   featured:false },
  { id:'snowbattle',               name:'Snow Battle',                cat:'Ação',       tags:['neve','batalha'],          featured:false },
  { id:'soccerrandom',             name:'Soccer Random',              cat:'Esporte',    tags:['futebol'],                 featured:false },
  { id:'solitaire',                name:'Solitaire',                  cat:'Casual',     tags:['cartas'],                  featured:false },
  { id:'spacecompany',             name:'Space Company',              cat:'Idle',       tags:['espaço'],                  featured:false },
  { id:'spacegarden',              name:'Space Garden',               cat:'Casual',     tags:['espaço'],                  featured:false },
  { id:'spacehuggers',             name:'Space Huggers',              cat:'Ação',       tags:['espaço','shooter'],        featured:false },
  { id:'spaceinvaders',            name:'Space Invaders',             cat:'Clássico',   tags:['espaço'],                  featured:false },
  { id:'stack',                    name:'Stack',                      cat:'Casual',     tags:['empilhar','3D'],           featured:false },
  { id:'stackball',                name:'Stack Ball',                 cat:'Casual',     tags:['bola','torre'],            featured:false },
  { id:'stickman-hook',            name:'Stickman Hook',              cat:'Ação',       tags:['gancho','swing'],          featured:true  },
  { id:'stickmanboost',            name:'Stickman Boost',             cat:'Plataforma', tags:['parkour'],                 featured:false },
  { id:'stickmanclimb',            name:'Stickman Climb',             cat:'Plataforma', tags:['escalar'],                 featured:false },
  { id:'stickmangolf',             name:'Stickman Golf',              cat:'Esporte',    tags:['golfe'],                   featured:false },
  { id:'stickmanhook',             name:'Stickman Hook 2',            cat:'Ação',       tags:['gancho'],                  featured:false },
  { id:'stickmansurvival',         name:'Stickman Survival',          cat:'Ação',       tags:['sobrevivência'],           featured:false },
  { id:'subwaysurfers',            name:'Subway Surfers',             cat:'Corrida',    tags:['runner','metro'],          featured:true  },
  { id:'subwaysurfersny',          name:'Subway Surfers NY',          cat:'Corrida',    tags:['runner'],                  featured:false },
  { id:'subwaysurferssingapore',   name:'Subway Surfers Singapore',   cat:'Corrida',    tags:['runner'],                  featured:false },
  { id:'tanukisunset',             name:'Tanuki Sunset',              cat:'Corrida',    tags:['longboard'],               featured:false },
  { id:'tetris',                   name:'Tetris',                     cat:'Clássico',   tags:['blocos'],                  featured:false },
  { id:'themazeofspacegoblins',    name:'Maze of Space Goblins',      cat:'Aventura',   tags:['labirinto','espaço'],      featured:false },
  { id:'timeshooter',              name:'Time Shooter',               cat:'Ação',       tags:['tempo','fps'],             featured:true  },
  { id:'timeshooter2',             name:'Time Shooter 2',             cat:'Ação',       tags:['tempo','fps'],             featured:false },
  { id:'timeshooter3',             name:'Time Shooter 3',             cat:'Ação',       tags:['tempo','fps'],             featured:false },
  { id:'tinyfishing',              name:'Tiny Fishing',               cat:'Casual',     tags:['pesca'],                   featured:false },
  { id:'tombofthemask',            name:'Tomb of the Mask',           cat:'Ação',       tags:['labirinto'],               featured:false },
  { id:'topspeedracing3d',         name:'Top Speed Racing 3D',        cat:'Corrida',    tags:['3D'],                      featured:false },
  { id:'towermaster',              name:'Tower Master',               cat:'Casual',     tags:['torre'],                   featured:false },
  { id:'trimps',                   name:'Trimps',                     cat:'Idle',       tags:['rpg'],                     featured:false },
  { id:'tunnelrush',               name:'Tunnel Rush',                cat:'Ação',       tags:['túnel','velocidade'],      featured:true  },
  { id:'vex3',                     name:'Vex 3',                      cat:'Plataforma', tags:['obstáculos'],              featured:false },
  { id:'vex4',                     name:'Vex 4',                      cat:'Plataforma', tags:['obstáculos'],              featured:false },
  { id:'vex5',                     name:'Vex 5',                      cat:'Plataforma', tags:['obstáculos'],              featured:false },
  { id:'vex6',                     name:'Vex 6',                      cat:'Plataforma', tags:['obstáculos'],              featured:false },
  { id:'webecomewhatwebehold',     name:'We Become What We Behold',   cat:'Aventura',   tags:['mensagem'],                featured:false },
  { id:'worldshardestgame2',       name:"World's Hardest Game 2",     cat:'Puzzle',     tags:['difícil'],                 featured:false },
  { id:'xx142b2exe',               name:'XX142-B2.exe',               cat:'Terror',     tags:['pixel','horror'],          featured:false },
  { id:'zombsroyale',              name:'ZombsRoyale.io',             cat:'Ação',       tags:['battle royale','io'],      featured:true  },
];

const CATEGORIES = ['Todos','Ação','Aventura','Casual','Clássico','Corrida','Esporte','Estratégia','Idle','Plataforma','Puzzle','Ritmo','RPG','Simulação','Terror'];

function getGameUrl(id) {
  return `${BASE_URL}/${id}/index.html`;
}

function getGameEmoji(cat) {
  const map = {
    'Ação':'⚔️','Aventura':'🗺️','Casual':'🎲','Clássico':'👾',
    'Corrida':'🏎️','Esporte':'⚽','Estratégia':'♟️','Idle':'⏱️',
    'Plataforma':'🏃','Puzzle':'🧩','Ritmo':'🎵','RPG':'⚔️',
    'Simulação':'🏙️','Terror':'👻'
  };
  return map[cat] || '🎮';
}
